palavra = (input('Porfavor, digite uma palavra'))
print(' o tipo da palavra {} e igual a '.format(palavra), type(palavra))
print('A palavra {} contem espaço '.format(palavra), palavra.isspace())
print('A palavra {} é numero? '.format(palavra), palavra.isnumeric())
print('A palavra {} é alfabetica? '.format(palavra), palavra.isalpha())
print('A palavra {} é alfanumerica? '.format(palavra), palavra.isalnum()) 
print('A palavra {} contem maiusculas? '.format(palavra), palavra.isupper())
print('A palavra {} contem minusculas? '.format(palavra), palavra.islower())
print('A palavra {} é capitalizada? '.format(palavra), palavra.istitle())
